# models & weights
model_cfg: "params/model/edgeyolo.yaml"
weights: "./train_output/edgeyolo/last.pth"      # it contains models config, set null if not use it
use_cfg: false                                   # force using cfg file data instead of cfg in weights

# output
output_dir: "./train_output/edgeyolo"
save_checkpoint_for_each_epoch: true
log_file: "log.txt"

# dataset
dataset_dir: "/dataset/coco2017"
train_dir: "train2017"
val_dir: "val2017"
train_anno_file: "annotations/instances_train2017.json"
val_anno_file: "annotations/instances_val2017.json"
class_names_file: "classes.txt"        # this file is in dataset dir
use_segmentation: false                # use segmentation labels to generate bbox instead of using bbox labels directly.

# dataloader
batch_size_per_gpu: 8
loader_num_workers: 4
num_threads: 1

# device & data type
device: [0, 1, 2, 3]
fp16: false
cudnn_benchmark: false    # set true if multiscale_range is set zero

## train hyper-params
optimizer: "Adam"
max_epoch: 400            # 300
close_mosaic_epochs: 15

# learning rate
lr_per_img: 0.00015625
warmup_epochs: 5
warmup_lr_ratio: 0.0
final_lr_ratio: 0.01      # 0.05   (if epoch is 300)

# training/dataset enhancement
#      [cls_loss, conf_loss, iou_loss]
loss_use: ["bce", "bce", "giou"]   # bce: BCE loss. bcf: Balanced Focal loss. hyb: HR loss, iou, c/g/siou is available

input_size: [640, 640]
multiscale_range: 5
weight_decay: 0.0005
momentum: 0.9
use_ema: true
enable_mixup: true
mixup_scale: [0.5, 1.5]
mosaic_scale: [0.1, 2.0]
flip_prob: 0.5
mosaic_prob: 1
mixup_prob: 1
degrees: 10

# evaluate
eval_at_start: false
val_conf_thres: 0.01
val_nms_thres: 0.65
eval_only: false                # running benchmark only for all weights in output_dir

# show
print_interval: 10

# others
load_optimizer_params: true     # load optimizer params when resume train, set false if there is an error.
train_backbone: true            # set false if you only want to train head
train_start_layers: 51          # when not train backbone, train layers starts from this layer, see params/models/edgeyolo.yaml
force_start_epoch: -1           # set -1 to disable this option
